### ISSUE TITLE
Integration with parent Ember project?

### ISSUE THREAD

**Issue by ryanlitalien** [201-created/ember-hexo-blog#1]
Hi there, I see at the moment that this is just a wrapper around hexo. Any plans to integrate it into the parent Ember project? Mainly by modifying (or adding) routes based on the `root` option in `_config.yml`? Out of the box, the links in the template don't work as they're using directory style links.

http://localhost:4200/blog/tags

![image](https://user-images.githubusercontent.com/1479756/29802614-7b76fc2a-8c44-11e7-9a47-cb7f06125ae0.png)

Thanks!

**Comment by mixonic** [comment]
@ryanlitalien If the Ember app uses hash based routing then links to the `/blog` path will just work.

I suppose we could add a few helpers that make linking to the blog or posts from the main app easier.

**Comment by ryanlitalien** [comment]
I'm not using hash routing. I've been messing around with the `beforeModel()` with a redirect to the index.html on a "blog" route. Any tips or suggestions on a more formal way?

**Comment by ryanlitalien** [comment]
I'm moving my blog out of the Ember project, as it's essentially two different "applications."
